spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/msa/product
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: optional:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: validate # 여러 instance 접근 시 DDL은 못 건들게하기
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
server:
  port: 19093