server:
  port: 19091

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: order-service  # ??? ???
              uri: lb://order-service  # 'orders-service'?? ???? ?? ???? ???? ???
              predicates:
                - Path=/order/** #/orders/** ??? ???? ??? ? ???? ??
            - id: product-service  # ??? ???
              uri: lb://product-service # 'users-service'?? ???? ?? ???? ???? ???
              predicates:
                - Path=/product/** # /users/** ??? ???? ??? ? ???? ??
          discovery:
            locator:
              enabled: true  # ??? ?????? ?? ???? ???? ????? ??

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

