spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/msa/order
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: optional:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=60s
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
server:
  port: 19092
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
