spring:
  application:
    name: auth-service
  config:
    import: optional:.env[.properties]
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

service:
  jwt:
    access-expiration: ${JWT_EXPIRATION}
    secret-key: ${JWT_KEY}
