spring:
  application:
    name: auth-service
  config:
    import: optional:.env[.properties]
  datasource:
    url: jdbc:mysql://localhost:3306/msa/user
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

service:
  jwt:
    access-expiration: ${JWT_EXPIRATION}
    secret-key: ${JWT_KEY}
server:
  port: 19095
